## 20 inbuilt method in Pandas

In [37]:
import pandas as pd

In [38]:
fileName = 'housing.csv'


In [39]:
filePath = 'C:\housing.csv'


In [40]:
fileDir = filePath + ' / ' + fileName

In [41]:
fileDir

'C:\\housing.csv / housing.csv'

In [ ]:
fileDir = filePath + ' / ' + fileName
df = pd.read_csv(fileDir)


In [ ]:
#number 1
#loading the data from a csv file. They are used to read a CSV or an excel file to a pandas DataFrame format. 

import pandas as pd

df = pd.read_csv(filename

print(df.to_string())


In [ ]:
#Number 2

 df.columns

when you have a big dataset like that it can be hard to see all the columns. using .columns function, you can print out
all the columns of the dataset:
    df.columns

In [ ]:
#Number 3
df.drop()

You can drop some unnecessary columns using df.drop()

df.drop()

In [ ]:
#Number 4

len()

Provides with the length of the DataFrame. 
len(df)

In [ ]:
#Number 5
df.query()
You can filter or query using a boolean expression

In [ ]:
#Number 6
 df[‘’].dtypes
This is used to know the data types of the variables before diving into the analysis, visualization, or predictive modeling. 

In [ ]:
#number 7
10. df.insert()

As the name of the function suggests, it inserts a column in the specified position.
To demonstrate that I will first create an array of random numbers that have the length of our DataFrame:

In [ ]:
#Number 8
11. df[‘’].cumsum()

It provides you with the cumulative sum.

In [ ]:
#Number 9
df.sample()

When the size of the dataset is too big, you can take a representative sample from it to perform the analysis and predictive
modeling.

In [ ]:
#Number 10
df[‘’].where()

This function helps you query a dataset based on a boolean condition. 

In [ ]:
#Number 11
df[‘’].unique()

This is very useful where we have categorical variables. It is used to find out the unique values of a categorical column

In [ ]:
#Number 12
 df[‘’].nunique()

This function lets you know how many unique values do you have in a column. 

In [ ]:
#Number 13
 df[‘’].rank()

This function provides you with the rank based on a certain column. 

In [ ]:
#number 14
df.replace()

 It replaces the values of a column.

In [ ]:
#number 14
.isin()

I am going to make a subset of the dataset that will contain only a few nationalities of players using .isin() function

In [ ]:
#Number 15
df.rename()

It is used to rename the column/s. 

In [ ]:
#number16
df.groupby()

This is the most popular function for data summarizing.

In [ ]:
#number 17
.pct_change()

You can get the percent change from the previous value of a variable. 

In [ ]:
#number18
 df.count()

It provides you the number of data in the DataFrame in the specified direction. When the direction is 0, it provides the number
of data in the columns:

In [ ]:
#number 19
 pd.crosstab()

It gives you a frequency table that is a cross-tabulation of two variables. 

In [ ]:
#number 20
df[‘’].describe()

This is a great function that provides some basic statistical measures. 

## 20 inbuilt methods in Numpy

In [5]:
import numpy as np

In [10]:
#number 1
#From Python List
#To create a NumPy array from a given Python list, use the np.array() method:

numbers = [5,6,7,8,9]

np_array = np.array(numbers)
np_array

array([5, 6, 7, 8, 9])

In [11]:
#number2
#We can verify the type of the object created and the datatype using the type() method and dtype attribute respectively

print("The type of object:", type(np_array))
print("The Datatype of the NumPy array:", np_array.dtype)

The type of object: <class 'numpy.ndarray'>
The Datatype of the NumPy array: int32


In [ ]:
#number 3
#Regularly Incrementing Numbers
#To create an array with regularly incrementing values, use the np.arange() method.



In [12]:
#number 4
#indexing in numpy
#You can access an array element by referring to its index number.

import numpy as np

arr = np.array(['john','tobi','samson','ajala'])

print(arr[2]) 

samson


In [14]:
#number5
#The NumPy array object has a property called dtype that returns the data type of the array:

import numpy as np

arr = np.array([3.5,4.6])

print(arr.dtype)

float64


In [ ]:
#number 6
#.copy()
# the copy is a new array


In [17]:
#number 7
# shape
#The shape of an array is the number of elements in each dimension.
#print the shape of a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [18]:
#number8
#np.linspace() metho
#If you want to create a NumPy array with a specific number of elements that are spaced equally in a given range of values, 
#use the np.linspace() method:

np.linspace(start = 1, stop = 10, num = 15)
    

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [20]:
#number9
#np.logspace() method
# if you want to generate numbers that are equally apart in the logarithmic space, use the np.logspace() method:

np.logspace(start = 1, stop = 6, num = 8, base = 2)




array([ 2.        ,  3.28134142,  5.38360077,  8.83271611, 14.49157863,
       23.77590863, 39.00843693, 64.        ])

In [21]:
#number 10
#Identity Array
#To create the identity NumPy Matrix, use the np.identity() method:

np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#number 11
#np.eye() method.
#To create a 2-dimensional NumPy Array (of any shape) with ones on the diagonal and zeros elsewhere, use the np.eye() method.

np.eye(N = 4, M = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
#number 12
#np.ones() method
#To create a NumPy array filled with ones, use the np.ones() method as demonstrated below:

np.ones((7, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
#number13
#np.full() method.
#To create a NumPy array filled with values other than zeros and ones, use the np.full() method.

np.full((2, 6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [27]:
#number 14
#np.empty() method:
# if you want to create a NumPy array of a given shape and type without initializing entries, use the np.empty() method:

np.empty((2, 6), np.int16)


array([[    0,     0,     0, 16368,     0,     0],
       [    0, 16368,     0,     0,     0, 16368]], dtype=int16)

In [29]:
#number 15
#np.ones_like() method:
#If you want to create a NumPy array of ones with a shape similar to that of another NumPy array, use the np.ones_like() method:

np_array = np.array([[1,2,3], [4,5,6]])

np.ones_like(np_array)

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
#number 16
# np.zeros_like() method
# if you want to create a NumPy array of zeros that takes the shape of another NumPy array, use the np.zeros_like() method

np_array = np.array([[2], [6]])

np.zeros_like(np_array)

array([[0],
       [0]])

In [31]:
#number 17
#np.random.randn() method.
#To generate a random NumPy array from a Normal Distribution with µ=0 and σ = 1 use the np.random.randn() method.

np.random.randn(6)





array([ 0.83275249,  0.11228137, -0.57331471,  0.98083129, -0.74041255,
       -0.27714324])

In [33]:
#number 18
#np.fromstring() method:
#To create a 1-dimensional NumPy array from text data in a string, use the np.fromstring() method:

string = "10 12"
np.fromstring(string, sep = " ")



array([10., 12.])

In [34]:
#number 19
#p.diag() method:
#You can create a square 2-dimensional NumPy array with specific values along the diagonal using the np.diag() method:

diag = [2, 8, 3, 4]
np.diag(diag)

array([[2, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])